### ISSUE TITLE
Can't open /home/xxx/IMPACT_central.log (No such file or directory) 

### ISSUE THREAD

**Issue by twelvesummer** [rhshah/IMPACT-Pipeline#1]
When I run this script that returned an exception to me.

> Can't open /home/xxx/IMPACT_central.log (No such file or directory) at /IMPACT-Pipeline-1.0.1/sofeware/localperl/lib/site_perl/5.20.2/Log/Log4perl/Appender/File.pm line 151.
> BEGIN failed--compilation aborted at /data/PRO/pro_cancer/pipeline/IMPACT-Pipeline-1.0.1/bin/RunIlluminaProcess.pl line 111.

As you know, a part of Linux systems set $HOME not equal '/home/yourname/'. I found the bug in the below script.
https://github.com/rhshah/IMPACT-Pipeline/blob/7b34bffb4761f67b19583746b296e5ce381f59e2/custom_perl_module/MSKCC_DMP_Logger.pm#L156

fix below:
```
my $uName = `echo \$HOME`;
```

**Comment by rhshah** [comment]
Thanks for reporting, but this does not work as a drop-in solution. Please modify it for your use.
